server.tomcat.additional-tld-skip-patterns=htmlunit-*.jar,jetty-*.jar
server.port=8080

spring.datasource.url=jdbc:hsqldb:file:./data/sicae-db;shutdown=true
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never